/*Database*/
(list([hiring_for_unlawful_asssembly(hel),believes_to_be_acting(hel),done_in_pursuant_to_or_order_of_Court(hel)])).
(list([bound(lea),mistake_of_fact(lea),not_mistake_of_law(lea),good_faith(lea)])).
list([done_by_accident(ayush),without_criminal_intention(ayush),lawful_act(ayush)]).
(list([multiple_persons(ravi),fighting_in_public(ravi),disturb_peace(ravi)])).
list([aiding_escape_prisoner(teja),rescue_prisoner(teja),(harbour_prisoner(teja))]).
(list([immature_understanding(temp),child_more_than_seven_less_than_twelve(temp),incapable_of_judgement(temp)])).
list([cause_harm(ram),rape(ram)]).
(list([abetment(hari),death_or_life_imprisonment_offences(hari)])).
list([abetting(sri),different_act_done(sri)]).
